<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-JJT0LPU" ignored="0" name="Test" tests="5" failures="1" timestamp="2022-08-26T11:39:21 IST" time="0.1" errors="0">
  <testcase name="login" time="0.014" classname="com.TestNG_.I_Retry_Analyser"/>
  <testcase name="number" time="0.003" classname="com.TestNG_.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- number -->
  <testcase name="number" time="0.002" classname="com.TestNG_.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- number -->
  <testcase name="number" time="0.002" classname="com.TestNG_.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- number -->
  <testcase name="number" time="0.002" classname="com.TestNG_.I_Retry_Analyser">
    <failure type="java.lang.AssertionError" message="expected [123] but found [321]">
      <![CDATA[java.lang.AssertionError: expected [123] but found [321]
at com.TestNG_.I_Retry_Analyser.number(I_Retry_Analyser.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- number -->
</testsuite> <!-- Test -->
